name: BridgingSkin
main: ldcr.BridgingSkin.BridgingSkin
version: 1.0.0
author: Ldcr
depend: ["LdcrUtils"]
commands:
  bskin:
    description: Choose your skin.
    usage: /bskin
  bskin-edit:
